name: Node CI

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node_modules
        with:
          path: node_modules
          key: gas-pjc-tests-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            gas-pjc-tests-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
            gas-pjc-tests-${{ env.cache-name }}-
            gas-pjc-tests-

      - run: yarn install

      - run: yarn run lint

      - name: Slack Notification
        uses: homoluctus/slatify@v1.5
        if: failure()
        with:
          job_name: '*${{ github.workflow }}*'
          type: ${{ job.status }}
          icon_emoji: ":octocat:"
          url: ${{ secrets.SLACK_WEBHOOK }}
